---

name: Pull Request Validator
description: GitHub Action that validates if PR complies with provided requirements

branding:
  icon: git-pull-request
  color: blue

inputs:
  pr-metadata:
    required: true
    description: Pull Request metadata
  config-path:
    required: true
    default: .github/pull-request-validator.yml
    description: Path to configuration file

  required-approvals:
    default: '1'
    description: Number of required approvals

  set-status:
    required: true
    default: 'false'
    description: Set check-run status on Pull Request
  status-title:
    required: false
    default: Pull Request validation
    description: H3 title of status message

  token:
    required: true
    description: GitHub TOKEN or PAT

outputs:
  status:
    description: Status message of the validation

runs:
  using: node20
  main: dist/index.js
